Repository Dongmanee/backend, pull requests merged in 2023-11, with the labels that each got.

#6 chore: PasswordEncoder import 문 제거
  dongmanee/src/test/java/com/dongmanee/domain/member/controller/MemberControllerTest.java
Labels: 🪣CHORE

#8 feat: create club entity
  dongmanee/src/main/java/com/dongmanee/domain/club/domain/Club.java
  dongmanee/src/main/java/com/dongmanee/domain/club/domain/ClubCategory.java
  dongmanee/src/main/java/com/dongmanee/domain/club/domain/ClubSns.java
  dongmanee/src/main/java/com/dongmanee/domain/club/domain/ClubUser.java
  dongmanee/src/main/java/com/dongmanee/domain/club/enums/ClubRole.java
  dongmanee/src/main/java/com/dongmanee/domain/member/domain/Member.java
Labels: ✨FEAT

#9 feat: create university entity
  dongmanee/src/main/java/com/dongmanee/domain/club/domain/Club.java
  dongmanee/src/main/java/com/dongmanee/domain/member/domain/Member.java
  dongmanee/src/main/java/com/dongmanee/domain/member/mapper/MemberMapper.java
  dongmanee/src/main/java/com/dongmanee/domain/university/dao/UniversityRepository.java
  dongmanee/src/main/java/com/dongmanee/domain/university/domain/University.java
  dongmanee/src/main/java/com/dongmanee/domain/university/exception/UniversityIdExistsException.java
  dongmanee/src/main/java/com/dongmanee/domain/university/mapper/UniversityMapper.java
  dongmanee/src/main/resources/import.sql
Labels: ✨FEAT

#13 feat: jwt local login
  dongmanee/build.gradle
  dongmanee/src/main/java/com/dongmanee/domain/member/dao/MemberRepository.java
  dongmanee/src/main/java/com/dongmanee/domain/member/enums/Role.java
  dongmanee/src/main/java/com/dongmanee/domain/member/service/MemberServiceImpl.java
  dongmanee/src/main/java/com/dongmanee/global/security/config/SecurityConfig.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/controller/SignInController.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/controller/port/SignInService.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/domain/MemberDetails.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/dto/request/SignInRequest.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/dto/response/JwsToken.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/entrypoint/CustomAuthenticationEntryPoint.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/exception/CustomAccessDeniedException.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/exception/CustomAuthenticationException.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/exception/PasswordUnMatchException.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/exception/UnAuthorizedException.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/filter/JwtAuthenticationFilter.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/handler/CustomAccessDeniedHandler.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/provider/JwtProvider.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/service/SignInServiceImpl.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/service/UserDetailLoginService.java
  dongmanee/src/main/java/com/dongmanee/global/security/login/service/port/LoginMemberRepository.java
  dongmanee/src/main/resources/application-dev.yaml
  dongmanee/src/main/resources/application.yml
Labels: ✨FEAT, 🛠️FIX

#17 feat: SecurityContext에 인증객체 생성 및 JWT인증 예외 처리
  dongmanee/src/main/java/com/dongmanee/domain/member/controller/MemberController.java
  dongmanee/src/main/java/com/dongmanee/domain/security/config/SecurityConfig.java
  dongmanee/src/main/java/com/dongmanee/domain/security/exception/CustomJwtException.java
  dongmanee/src/main/java/com/dongmanee/domain/security/filter/JwtExceptionFilter.java
  dongmanee/src/main/java/com/dongmanee/domain/security/provider/JwtProvider.java
  dongmanee/src/main/resources/application-dev.yaml
Labels: ✨FEAT
